[tool.coverage.run]
branch = true
source = [ "opentelemetry/instrumentation/runpod" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.poetry]
name = "opentelemetry-instrumentation-runpod"
version = "0.21.5"
description = "OpenTelemetry Runpod instrumentation"
authors = [ "Kartik Prajapati <kartik@ktklab.org>" ]
repository = "https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-runpod"
license = 'Apache-2.0'
readme = 'README.md'

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/runpod"

[tool.poetry.dependencies]
python = ">=3.9,<4"
opentelemetry-api = "^1.25.0"
opentelemetry-instrumentation = "^0.46b0"
opentelemetry-semantic-conventions = "^0.46b0"
opentelemetry-semantic-conventions-ai = "0.3.1"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.2.0"
flake8 = "7.0.0"
pytest = "^8.2.2"
pytest-sugar = "1.0.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.2"
pytest-sugar = "1.0.0"
vcrpy = "^6.0.1"
pytest-recording = "^0.13.1"
opentelemetry-sdk = "^1.23.0"
runpod = "^1.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
instruments = ["runpod"]

[tool.poetry.plugins."opentelemetry_instrumentor"]
runpod = "opentelemetry.instrumentation.runpod:RunpodInstrumentor"
